export const TOPICS_FETCH_TOPICS_BEGIN = 'TOPICS_FETCH_TOPICS_BEGIN';
export const TOPICS_FETCH_TOPICS_SUCCESS = 'TOPICS_FETCH_TOPICS_SUCCESS';
export const TOPICS_FETCH_TOPICS_FAILURE = 'TOPICS_FETCH_TOPICS_FAILURE';
export const TOPICS_FETCH_TOPICS_DISMISS_ERROR = 'TOPICS_FETCH_TOPICS_DISMISS_ERROR';
